name: CICD Node App

on:
    push:
        branches: [main]

jobs:

    build:

        runs-on: [ubuntu-latest]

        environment: testing

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Login Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image
              run: docker build -t blazerrt86899/nodejs-app .

            - name: Publish Image to Docker Hub
              run: docker push blazerrt86899/nodejs-app:latest
    
    deploy:

        needs: [build]

        runs-on: [gcp-ce]

        steps:
            - name: Installing Docker
              run: |
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo chmod 777 /var/run/docker.sock

            - name: Pull Image from Docker Hub
              run: docker pull blazerrt86899/nodejs-app:latest

            - name: Delete Old Container if available
              run: docker rm -f nodejs-app-container

            - name: Run Docker Container
              run: docker run -d -p 5000:5000 -name nodejs-app-container blazerrt86899/nodejs-app
